---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Главное меню с категориями и производителями одинаковое на всех страницах
  - Пользователь должен иметь возможность просмотра сайта на английском и русском языке
  - Пользователь должен иметь возможность возвращаться на определенную пронумерованную страницу поиска по товарам
  - При нажатии на кнопку добавить в корзину, открывается модальное окно, где можно ввести количество товара
  - В корзине есть возможность изменить количество товара
  - Для каждого товара в корзине корректно выводится название, цена и количество, которое было добавлено в корзину и общая сумма
  - Для каждого заказа есть кнопка для подробного просмотра заказа
  - Есть возможность удаления всех товаров в корзине
  - В корзине есть кнопка возврата в список товаров
